name: fruit_hub
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  flutter_svg: ^1.1.5
  ini: ^2.1.0
  sqflite: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/mocks/

  fonts:
    - family: TTNorms_Bold
      fonts:
        - asset: assets/fonts/TTNormsPro_Bold.ttf
          
    - family: TTNorms_Medium
      fonts:
        - asset: assets/fonts/TTNormsPro_Medium.ttf
          
    - family: TTNorms_Regular
      fonts:
        - asset: assets/fonts/TTNormsPro_Regular.ttf
          
    - family: TTNormsPro_Light
      fonts:
        - asset: assets/fonts/TTNormsPro_Light.ttf
